using Microsoft.AspNetCore.Mvc;
using System;

namespace Libraries.Extensions
{
    public class Request
    {
        /// <summary>Gets or sets the access token.</summary>
        /// <value>The access token.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for AccessToken
        public string AccessToken { get; set; }
        /// <summary>Gets or sets the time stamp.</summary>
        /// <value>The time stamp.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for TimeStamp
        public DateTime TimeStamp { get; set; }
        //public string TimeStamp { get; set; }
        /// <summary>Gets or sets the nonce.</summary>
        /// <value>The nonce.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Nonce
        public int Nonce { get; set; } = 0;
    }
    public class TRequest<T> : Libraries.Extensions.Request
    {
        public T value { get; set; }
    }
}
